
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxkrxfzigyqcgipudtlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4a3J4ZnppZ3lxY2dpcHVkdGxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzY3ODUsImV4cCI6MjA1NjkxMjc4NX0.tV2FMXQOndJEqJyi6v_SHxkECSAis_1HqL90oPoaKk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
